### ISSUE TITLE
npm install failed without babel-register package

### ISSUE THREAD

**Issue by yhBluescape** [amir20/phantomjs-node#442] opened 2016-04-12 22:19 UTC
### Expected behavior
npm install failed

### Actual behavior

see below whole screen capture
after npm install babel-register module, errors are gone 

### Steps to reproduce the behavior

1. [First Step] git clone 
2. [Second Step] npm install
3. [Other Steps...]

### Environment

- OS: OSX 10.11.3
- Node version (`node -v`): 4.3.2
- package version:
 
===========================
screen capture:

$ npm install

> phantom@2.0.10 prepublish /Users/yh.chang/test_pro/phantomjs-node
> gulp build

[15:05:30] Failed to load external module babel-register
[15:05:30] Failed to load external module babel-core/register
[15:05:30] Failed to load external module babel/register
/Users/yh.chang/test_pro/phantomjs-node/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import gulp from "gulp";
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/Users/yh.chang/test_pro/phantomjs-node/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/yh.chang/test_pro/phantomjs-node/node_modules/gulp/node_modules/liftoff/index.js:193:16)
    at module.exports (/Users/yh.chang/test_pro/phantomjs-node/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)

npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/yh.chang/.nvm/versions/node/v4.3.2/bin/node" "/Users/yh.chang/.nvm/versions/node/v4.3.2/bin/npm" "install"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! phantom@2.0.10 prepublish: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantom@2.0.10 prepublish script 'gulp build'.
npm ERR! This is most likely a problem with the phantom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantom
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yh.chang/test_pro/phantomjs-node/npm-debug.log

**Comment by amir20** [comment] 2016-04-12 22:51
What does `gulp -v` print?

**Comment by yhBluescape** [comment] 2016-04-12 23:53
The process are:
1. $ > git clone https://github.com/amir20/phantomjs-node.git
2. npm install

Then I got the errors as above, ...
 
After I do : 
npm install babel-register

then do:
 npm install

all errors are gone,...

**Comment by yhBluescape** [comment] 2016-04-13 22:48
Do we need to add babel-register on the package.json/devDependencies?
If one does the clone and npm install , the error will appear  again, looks like the gulp 3.9.1 need the babel-register,.. is it?

Thanks,

**Comment by amir20** [comment] 2016-04-13 23:40
I don't think we do because I can't reproduce this. Travis also doesn't fail without it. I am confused as to if this is needed. Happy to add it if you can find some more documentation about it.

**Comment by changyh** [comment] 2016-04-13 23:45
We have two people here verify the case, there are lots of google/discussing about gulp with babel-register issues,...

I tested it on ubuntu 14.04 and OSX 10.11.3,...

If you test it with gulp pre-install or just without gulp pre-install case,...

Thanks,

**Comment by amir20** [comment] 2016-04-13 23:58
Ok send me a pull request. I can merge. 

Sent via my iPhone

**Comment by amir20** [comment] 2016-04-14 21:44
I attempted to reproduce this with Docker and a fresh install of Ubuntu. I was not able to reproduce at all. After doing `npm install` I see

```
[21:42:38] Requiring external module babel-register
[21:42:38] Using gulpfile /phantomjs-node/gulpfile.babel.js
[21:42:38] Starting 'clean'...
[21:42:38] Finished 'clean' after 8.38 ms
[21:42:38] Starting 'build'...
[21:42:38] Finished 'build' after 426 ms
root@9db53bfd6417:/phantomjs-node# 
```
Which suggests it works just fine. I am closing this ticket and won't plan to add babel-register. Perhaps you can try to give me a `Dockerfile` or some other way of reproducing this as I can't reproduce it.

**Closed by amir20** 2016-04-14 21:44 UTC

**Comment by yhBluescape** [comment] 2016-04-14 22:20
I can't push to origin by get the following error:
remote: Permission to amir20/phantomjs-node.git denied to yhBluescape.
fatal: unable to access 'https://github.com/amir20/phantomjs-node.git/': The requested URL returned error: 403
-------------------------------
Here is the diff and I tested on OSX and ubuntu 14.0.4
diff --git a/package.json b/package.json
index 27a1844..14e4fa2 100644
--- a/package.json
+++ b/package.json
@@ -31,6 +31,7 @@
   "devDependencies": {
     "babel-polyfill": "^6.5.0",
     "babel-preset-es2015": "^6.5.0",
+    "babel-register": "^6.7.2",
     "del": "^2.2.0",
     "gulp": "^3.9.1",
     "gulp-babel": "^6.1.2",

**Comment by amir20** [comment] 2016-04-15 00:01
You have to send me a pull request. You don't have permission to push to this repo. But based off what I found, I don't think this is a issue.
