### ISSUE TITLE
phantomjs-node crashes ChildProcess when wrapped in concurrency

### ISSUE THREAD

**Issue by RavenHursT** [amir20/phantomjs-node#280] opened 2015-05-28 02:54 UTC
I have a simple app that does the following:

````javascript
    var
        phantom = require('phantom'),
        express = require('express'),
        serve = express();
    
    serve.get('/foo', function (req, res) {
        try {
            phantom.create(function (ph) {
                console.log('Phantom browser created w/ pid: ', ph.process.pid);
                ph.onError = function (msg, trace) {
                    var msgStack = ['PHANTOM ERROR: ' + msg];
                    if (trace && trace.length) {
                        msgStack.push('TRACE:');
                        trace.forEach(function (t) {
                            msgStack.push(' -> ' + (t.file || t.sourceURL) + ': ' + t.line + (t.function ? ' (in function ' + t.function + ')' : ''));
                        });
                    }
                    console.log(msgStack.join('\n'));
                };
                ph.createPage(function(page){
                    page.open('http://www.stackoverflow.com', function(status){
                        res.json({pageStatus: status});
                        page.close();
                        ph.exit();
                    });
                });
            });
        } catch(e){
            console.log(e);
            throw e;
        }
        
    });
````

As long as I run this in WebStorm, it runs just fine and I can hit the ```/foo``` endpoint w/ as many concurrent requests as I want and everything works as expected.

But as soon as I try to scale it behind PM2 (https://github.com/Unitech/pm2, a process manager that utilizes the node-cluster module) w/ ```pm2 start -i 0 phantomapp.js```, everything still works fine as long as I don't throw too many requests at it (I had a similar problem if I attempted to implement node-cluster myself in my script).  The second I open up two browser windows and hit refresh in both, I get the following in ```pm2 logs```.  At which point, ALL 8 processes managed by PM2 just "disappear".

````
    PM2: 2015-05-27 18:53:17: [PM2] Error caught by domain:
    PM2: AssertionError: false == true
    PM2:     at RoundRobinHandle.add (cluster.js:140:3)
    PM2:     at queryServer (cluster.js:480:12)
    PM2:     at Worker.onmessage (cluster.js:438:7)
    PM2:     at ChildProcess.<anonymous> (cluster.js:692:8)
    PM2:     at ChildProcess.emit (events.js:129:20)
    PM2:     at handleMessage (child_process.js:324:10)
    PM2:     at Pipe.channel.onread (child_process.js:352:11)
    PM2: 2015-05-27 18:53:18: [PM2] Automatic `pm2 update` failed. Killing PM2 daemon and its processes...
    PM2: 2015-05-27 18:53:18: pm2 has been killed by signal, dumping process list before exit...
    PM2: 2015-05-27 18:53:18: Stopping app:phantomapp id:0
    PM2: assert.js:86
    PM2:   throw new assert.AssertionError({
    PM2:         ^
    PM2: AssertionError: false == true
    PM2:     at RoundRobinHandle.add (cluster.js:140:3)
    PM2:     at queryServer (cluster.js:480:12)
    PM2:     at Worker.onmessage (cluster.js:438:7)
    PM2:     at ChildProcess.<anonymous> (cluster.js:692:8)
    PM2:     at ChildProcess.emit (events.js:129:20)
    PM2:     at handleMessage (child_process.js:324:10)
    PM2:     at Pipe.channel.onread (child_process.js:352:11)
    phantomapp-0 (err): Process disconnected from parent !
    PM2: [PM2] Spawning PM2 daemon
    PM2: 2015-05-27 18:53:18: [PM2][WORKER] Started with refreshing interval: 30000
    PM2: 2015-05-27 18:53:18: [[[[ PM2/God daemon launched ]]]]
    PM2: 2015-05-27 18:53:18: BUS system [READY] on port /Users/matthewmarcus/.pm2/pub.sock
    PM2: 2015-05-27 18:53:18: RPC interface [READY] on port /Users/matthewmarcus/.pm2/rpc.sock
    PM2: [PM2] PM2 Successfully daemonized
    PM2: Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
    PM2: [PM2] Stopping PM2...
    PM2: [PM2][WARN] No process found
    PM2: [PM2] All processes have been stopped and deleted
    PM2: 2015-05-27 18:53:18: PM2 is being killed via kill method
    PM2: 2015-05-27 18:53:18: RPC socket closed
    PM2: 2015-05-27 18:53:18: PUB socket closed
    PM2: [PM2] PM2 stopped
    PM2: 2015-05-27 18:53:19: [PM2][WORKER] Started with refreshing interval: 30000
    PM2: 2015-05-27 18:53:19: [[[[ PM2/God daemon launched ]]]]
    PM2: 2015-05-27 18:53:19: BUS system [READY] on port /Users/matthewmarcus/.pm2/pub.sock
    PM2: 2015-05-27 18:53:19: RPC interface [READY] on port /Users/matthewmarcus/.pm2/rpc.sock
    PM2: >>>>>>>>>> PM2 updated
    PM2: ┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬────────┬──────────┐
    PM2: │ App name │ id │ mode │ pid │ status │ restart │ uptime │ memory │ watching │
    PM2: └──────────┴────┴──────┴─────┴────────┴─────────┴────────┴────────┴──────────┘
    PM2:  Use `pm2 show <id|name>` to get more details about an app
````

It appears that the call to spawn() ends up throwing this error for some reason.

Related SO question: http://stackoverflow.com/questions/30496072/phantomjs-node-crashes-when-attempting-to-scale-behind-node-cluster

**Comment by RavenHursT** [comment] 2015-05-28 03:36
You can reproduce the same issue using just node-native cluster:

````javascript
var cluster = require('cluster');

if(cluster.isMaster){
    var cpuCount = require('os').cpus().length;

    for (var i = 0; i < cpuCount; i++){
        cluster.fork();
    }

    cluster.on('exit', function(worker){
        console.log('Worker ' + woker.id + ' died. Forking...');
        cluster.fork();
    });

} else {
    var
        phantom = require('phantom'),
        express = require('express'),
        serve = express();
    
    serve.get('/foo', function (req, res) {
        try {
            phantom.create(function (ph) {
                console.log('Phantom browser created w/ pid: ', ph.process.pid);
                ph.onError = function (msg, trace) {
                    var msgStack = ['PHANTOM ERROR: ' + msg];
                    if (trace && trace.length) {
                        msgStack.push('TRACE:');
                        trace.forEach(function (t) {
                            msgStack.push(' -> ' + (t.file || t.sourceURL) + ': ' + t.line + (t.function ? ' (in function ' + t.function + ')' : ''));
                        });
                    }
                    console.log(msgStack.join('\n'));
                };
                ph.createPage(function(page){
                    page.open('http://www.stackoverflow.com', function(status){
                        res.json({pageStatus: status});
                        page.close();
                        ph.exit();
                    });
                });
            });
        } catch(e){
            console.log(e);
            throw e;
        }
        
    });
}
````

Produces the following error in the console when attempting to handle more than 1 request at a time:

````
assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: false == true
    at RoundRobinHandle.add (cluster.js:140:3)
    at queryServer (cluster.js:480:12)
    at Worker.onmessage (cluster.js:438:7)
    at ChildProcess.<anonymous> (cluster.js:692:8)
    at ChildProcess.emit (events.js:129:20)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)

Process finished with exit code 1
````

**Comment by mrchess** [comment] 2015-06-03 22:37
+1

**Comment by RavenHursT** [comment] 2015-06-04 04:02
I solved this issue using https://github.com/baudehlo/node-phantom-simple and by upgrading phantomjs to 2.x.

**Comment by sfgxuan** [comment] 2015-08-07 07:15
I have exactly the same problem when using phtomjs-node.
so the solution  is "do not use phantomjs-node, use node-phantom-simple"?
can't the problem be solved in phantomjs-node?

**Comment by RavenHursT** [comment] 2015-08-10 19:34
I just gave up.. tried another library, and it works just fine.

**Comment by frankred** [comment] 2015-11-06 11:30
Are there any news here? :(

**Comment by abhilashsajeev** [comment] 2016-01-31 13:32
Its been long time . What is the status on this issue. Moving to node-phantom-simple is the only solution?

**Comment by amir20** [comment] 2016-01-31 16:34
I have gone through the code a few times. I imagine this is happening because somewhere `cb` is being saved to be used later. But I can't find any instances of that happening. I am open to suggestions to try new things. As far as I know, the other libraries spawn a new process via `child_process` so it works differently.

**Comment by amir20** [comment] 2016-01-31 19:24
I was able to reproduce this bug by doing `node cluster.js` from https://gist.github.com/6f8329cc704ce9f713ad and running `siege -c10 -t20s http://localhost:3000/foo`. 

I saw this error
```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (/Users/amir.raminfar/Desktop/test_phantom/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/Users/amir.raminfar/Desktop/test_phantom/node_modules/express/lib/response.js:163:12)
    at ServerResponse.json (/Users/amir.raminfar/Desktop/test_phantom/node_modules/express/lib/response.js:249:15)
    at /Users/amir.raminfar/Desktop/test_phantom/cluster.js:38:29
    at Proto.apply (/Users/amir.raminfar/Desktop/test_phantom/node_modules/dnode-protocol/index.js:123:13)
    at Proto.handle (/Users/amir.raminfar/Desktop/test_phantom/node_modules/dnode-protocol/index.js:99:19)
    at D.dnode.handle (/Users/amir.raminfar/Desktop/test_phantom/node_modules/dnode/lib/dnode.js:140:21)
    at D.dnode.write (/Users/amir.raminfar/Desktop/test_phantom/node_modules/dnode/lib/dnode.js:128:22)
    at SockJSConnection.ondata (stream.js:31:26)
```

After much googling, I am not convinced this is related to phantom. I tried creating a new script without using `express` (https://gist.github.com/fe8b25bf4d6d6f8221e0) and that didn't break. I am going to investigate more but this is what I found so far.

**Comment by amir20** [comment] 2016-02-01 16:56
I feel like just rewriting all of this in es6 and testing it with `cluster` :P Sounds like a good weekend project. Does anybody else have any ideas before I take the most aggressive approach?

**Comment by abhilashsajeev** [comment] 2016-02-02 09:47
@amir20 You may try this with pm2. It also produces same error.

**Comment by manikandants** [comment] 2016-02-08 13:50
Any updates on this issue? I use [phantom-pdf](https://github.com/jnutter/phantom-pdf) and phantomjs in my application and I get the same error with node.js cluster.

**Comment by amir20** [comment] 2016-02-08 16:10
@manikandants No update yet. I am experimenting with rewriting this module. Right now it uses `dnode` which I don't think is very thread safe. I am trying to see if it works with `web sockets` which is the same method `poltergeist` uses to communicate.

**Comment by amir20** [comment] 2016-02-13 18:40
Try using `2.0.0-alpha. Should be fixed with cluster and pm2.

**Closed by amir20** 2016-02-13 18:40 UTC

**Comment by amir20** [comment] 2016-02-15 01:25
I stress tested the new version with `cluster` for 30 seconds. It worked without any errors. 

```
$ siege -c 10 -t 20s http://localhost:3000/foo
Lifting the server siege...      done.

Transactions:		          68 hits
Availability:		      100.00 %
Elapsed time:		       19.54 secs
Data transferred:	        0.00 MB
Response time:		        2.23 secs
Transaction rate:	        3.48 trans/sec
Throughput:		        0.00 MB/sec
Concurrency:		        7.77
Successful transactions:          68
Failed transactions:	           0
Longest transaction:	        3.08
Shortest transaction:	        1.16
```
