### ISSUE TITLE
.on() doesn't understand complex objects when passed in as 4th arg with runOnPhantom=true

### ISSUE THREAD

**Issue by daleyjem** [amir20/phantomjs-node#524] opened 2016-08-16 00:15 UTC
It doesn't appear that prototypical inheritance behaves correctly when an instantiated object is passed into the `page.on()` as a 4th arg.

Additionally... If instead of using `.prototype`, `this.method` is placed inside of the constructor, it almost behaves as expected, except things like `RegExp` don't work.

### Expected behavior

**Case 1**
Passing in an instantiated object with prototype properties/methods is evaluated in the `.on()` callback with those same properties and methods still attached, when `runOnPhantom=true`

**Case 2**
If using `this.method` inside of a constructor function, that method should be able to execute a regular expression.

### Actual behavior

**Case 1**
The callback passing in the object fails to know about the extended properties/methods of the object.

**Case 2**
The regular expression fails to successfully `.test()`  

### Steps to reproduce the behavior

**Case 1**

1. Create a function with a prototype property and instantiate a new instance of it:

    ```javascript
    function Person(){}
    Person.prototype.name = "Jeremy";

    var person = new Person();
    ```

2. Listen on resource:

    ```javascript
    page.on('onResourceRequested', true, function(requestData, request, p) {
        console.log(p.name); // undefined
    }, person);
    ```

**Case 2**

1. Create a function with a property/method attached to `this`
    ```javascript
    function Person(){
        this.console = function(){
            console.log('hi');
        };

        this.regexp = new RegExp('jeremy', 'gi');
    }

    var person = new Person();
    ```

2. Listen on resource:

    ```javascript
    page.on('onResourceRequested', true, function(requestData, request, p) {
        p.console(); // info: hi
    	console.log( p.regexp.test('jeremy') ); // Doesn't do anything
    }, person);
    ```

### Environment

- OS: Mac
- Node version (`node -v`): 6.3.1
- package version: 2.1.1

**Comment by daleyjem** [comment] 2016-08-16 00:53
Long story short... while I can say `/css/.test( url )`, I need to be able to pass in a dynamic `RegExp` from a domain blacklist.

**Comment by daleyjem** [comment] 2016-08-16 01:29
I imagine it's because of some serialization stuff... stuff that's hard for me to wrap my own head around with a phantom/node bridge, so I hope @amir20 you don't think I'm ungrateful in the least for this module. For now, I'm using this, if it can help anyone else:

```
page.on('onResourceRequested', true, function(requestData, request, raw) {
    var url = requestData['url'];
    var regRaw = '(/' + raw + '/gi).test("' + url + '")';
    var isBlacklisted = eval(regRaw);
    if (isBlacklisted) {
        request.abort();
    }
}, blacklist.rawRegExp);
```

I know. I know. `eval()` is the devil.

**Comment by amir20** [comment] 2016-08-16 16:55
@daleyjem thanks for the details. I wasn't thinking you were ungrateful. I see you did a lot of research which is better than most! 

The issue is as you expected. It is because when `runOnPhantom=true` then everything is serialized as JSON to phantomjs. I use `JSON.stringify` where it probably doesn't honor `prototype` fields. 

I am curious to as why you can't just use RegExp in `onResourceRequested`.  That should theoretically work. Although, I haven't tried it. Something like

```js
page.on('onResourceRequested', true, function(requestData, request, regex) {
    var url = requestData['url'];
    var re = new RegExp(regex, 'ig');
    var isBlacklisted = re.test(url);
    if (isBlacklisted) {
        request.abort();
    }
}, regex);
```

**Comment by amir20** [comment] 2016-08-18 21:05
@daleyjem ping. I will close if you don't respond.

**Comment by daleyjem** [comment] 2016-08-18 21:09
`RegExp()` doesn't appear to be available within the callback

**Comment by amir20** [comment] 2016-08-18 21:11
Can you give me a minimum example to reproduce? Gist should work if you need multiple files.

**Comment by daleyjem** [comment] 2016-08-18 21:20
The example you gave would be sufficient enough to test.

**Comment by amir20** [comment] 2016-08-18 21:33
When I try that example, it works for me. I asked for a minimum example because I think there is something that you are doing different that is not working and the only way I can help is if I see it. But sadly, you just said my example is good enough. That doesn't really help. In the future, if you want help, you should provide full working example. Not just a snippet. 

I am closing because I can't reproduce.

**Closed by amir20** 2016-08-18 21:33 UTC
Labels: Cannot Reproduce

**Comment by daleyjem** [comment] 2016-08-18 22:10
I said your example was good enough, because that's literally what I was using before. Plus, my code is on my home computer and I'm at work. Thanks for your help anyway.
