### ISSUE TITLE
Counting the number of requests

### ISSUE THREAD

**Issue by jshemas** [amir20/phantomjs-node#438] opened 2016-04-07 23:00 UTC
So i'm trying count the number of requests that there are on a page when I load that page in phantomJS.

Here is the code I have tried:

```
var numberOfRequests = 0;
console.log('numberOfRequests-before:', numberOfRequests); // outputs 0
page.property('onResourceRequested', function () {
	numberOfRequests = numberOfRequests + 1;
});
console.log('numberOfRequests-after:', numberOfRequests); // outputs 0, should be some like 10
```

I've tried using the `createOutObject`, but that doesn't seem to work too well for me too. Also if I put a console log inside that function, (like `console.log('ping');`) i'll see many "pings."

Is there a easy way of getting this count?

### Environment

- OS: OSX 10.11.3
- Node version: v5.8.0
- package version: 2.0.10

**Comment by amir20** [comment] 2016-04-07 23:55
Can you show me how you did it with createOutObject?

**Comment by jshemas** [comment] 2016-04-08 00:20
Thanks for the quick reply!

Here is a fuller example of what i'm doing...

```
phantomSession.createPage().then(function (page) {
	var numberOfRequests = 0;
	page.property('onResourceRequested', function () {
		numberOfRequests = numberOfRequests + 1;
	});
	page.open(url).then(function (status) {
		var outObj = phantomSession.createOutObject();
		page.property('onResourceRequested', function (requestData, networkRequest, out) {
			out.count = out.count + 1;
		}, outObj);
		outObj.property('count').then(function (count) {
			console.log('count:', count); // count: undefined
		});
	});
});
```

**Comment by amir20** [comment] 2016-04-08 00:36
that's not the example with createOutObject. Your example won't work becauses that's a different context. Show me the out object instead and I could probably guess what you did wrong. I am away this week though so might take longer.

**Comment by amir20** [comment] 2016-04-08 00:36
Also search through the issues. There is a lot of examples.

**Comment by jshemas** [comment] 2016-04-08 00:42
I literally pull this from your readme:

```
var outObj = phInstance.createOutObject();
page.property('onResourceRequested', function(requestData, networkRequest, debug, out) {
    if(debug){      
      out.url = requestData.url;
    }
}, process.env.DEBUG, outObj);

outObj.property('url').then(function(url){
   console.log(url);
});
``` 

Is this not how you make a "createOutObject".....?

**Comment by jshemas** [comment] 2016-04-08 00:43
And I followed this ticket: https://github.com/amir20/phantomjs-node/issues/410

**Comment by amir20** [comment] 2016-04-08 02:13
Right that's the correct way to use it. But you said you tried it to count number of requests and it didn't work. The example you posted doesn't use out object. Your code doesn't use it correctly.

**Comment by amir20** [comment] 2016-04-09 22:36
@jshemas did you try something like this? 

```js
var outObject = phInstance.createOutObject();

outObject.count = 0;
page.property('onResourceRequested', function(requestData, networkRequest, out) {
    out.count += 1;
}, outObj);
```

**Comment by amir20** [comment] 2016-04-09 22:37
Marking as invalid until I can see your code. I can't reproduce it.

**Comment by amir20** [comment] 2016-04-11 19:35
Closing this ticket because there has been no response. We can reopen if needed.

**Closed by amir20** 2016-04-11 19:35 UTC
Labels: invalid

**Comment by jshemas** [comment] 2016-04-11 23:39
Okay, I was able to get it working with your above example plus:

```
outObject.property('count').then(function (count) {
	numberOfRequests = count;
});
```

Thanks.
