### ISSUE TITLE
phantom stdout: Error: cannot access member `url' of deleted QObject

### ISSUE THREAD

**Issue by angrytoro** [amir20/phantomjs-node#335] opened 2015-11-17 10:29 UTC
throw the error **phantom stdout: Error: cannot access member `url' of deleted QObject**
![image](https://cloud.githubusercontent.com/assets/1439721/11208980/42483680-8d59-11e5-937d-13dda33c3dad.png)

**Comment by jazzzz** [comment] 2015-11-17 10:50
Happens a lot to me. Also:
```
Error: cannot access member `content' of deleted QObject
Error: cannot access member `title' of deleted QObject
Error: cannot call function of deleted QObject
```

**Comment by amir20** [comment] 2015-11-17 16:01
When does this happen?

**Comment by jazzzz** [comment] 2015-11-17 16:31
When calling `page.get`, I don't know exactly when.

**Comment by angrytoro** [comment] 2015-11-18 10:46
@amir20 maybe when calling `page.get` or `page.open`, not very sure.

**Comment by jakob-erdmann** [comment] 2015-12-15 09:27
I am currently debugging a similar error

````
Error: cannot access member `loading' of deleted QObject
  :/ghostdriver/session.js:486 in _isLoading
  :/ghostdriver/session.js:222 in checkLoadingFinished
  :/ghostdriver/session.js:247
````

thrown when loading a new page. For me it only happens directly after switching to a new window. Looks like switching windows returns before all QObjects are loaded properly and thus invoking a page load is invoked on the old QObjects and fails when they are changed.

**Comment by amir20** [comment] 2016-02-21 02:55
This should be fixed because I can't reproduce it anymore.

**Closed** 2016-02-21 02:55 UTC
Labels: cannot reproduce
