### ISSUE TITLE
Add support for individual CookieJar's per WebPage

### ISSUE THREAD

**Issue by angustrau** [amir20/phantomjs-node#352] opened 2016-01-31 08:15 UTC
See ariya/phantomjs#11535

**Comment by gizmodude4** [comment] 2016-02-15 17:33
Do pages currently not share cookies?

**Comment by amir20** [comment] 2016-02-15 18:03
Which version are you talking about?

**Comment by gizmodude4** [comment] 2016-02-15 18:04
I'm interested in v2, but I"m not sure it's not super clear whether or not this issue is for V1 or V2

**Comment by amir20** [comment] 2016-02-15 18:53
I haven't supported cookies in v2 yet. I am actually working on that now. The problem is that v2 supports one `page` per instance`.  I can change it so it supports more. And then just share the cookie jar. What is your use case so that I know?

**Comment by gizmodude4** [comment] 2016-02-15 19:21
My use case is to have one phantom process with multiple pages each logged in to separate accounts for the same site. I can do it now with all separate phantom processes, but a problem I've been running in to is dangling processes here and there. That may be a problem with my implementation, but eliminating the variable of creating/destroying phantom processes would be more desirable

**Comment by amir20** [comment] 2016-02-15 20:43
So with the new version, each phantom instance should go away since it doesn't require a remote connection. I have ran many tests. As long as you call `phantom.exist()` it should exit correctly. I rather fix the problem of instances here than making cookies work. What do you think?

**Comment by gizmodude4** [comment] 2016-02-15 21:09
Sounds good to me, but @angustrau may have something to say. I kinda hijacked this issue and he may have a different use case than me

**Comment by amir20** [comment] 2016-02-15 22:40
@gizmodude4 see a707449. I added cookie support in v2.

**Comment by angustrau** [comment] 2016-02-15 23:49
How much overhead is added when using multiple Phantom instances vs multiple pages. My use case also involves signing in to a site with multiple accounts simultaneously. If the overhead of launching multiple instances is not too much, this could work for my use case, although I would prefer an option to have a cookie jar per page.

**Comment by amir20** [comment] 2016-02-16 02:39
@angustrau I can add it so that it has only one instance. That's how `phridge` works. But while testing, I found that creating only once instance wasn't the most efficient. Memory management on a long running process is unstable in my opinion. I felt it was safer to create a new instance. 

With that aside, I am curious about what your requirements are.  During my testing, I found that it was pretty fast. Below is 8 instances running for 30 seconds. It's about 3.5 requests per second. 

```
$ siege -c 10 -t 20s http://localhost:3000/foo
Lifting the server siege...      done.

Transactions:                 68 hits
Availability:             100.00 %
Elapsed time:              19.54 secs
Data transferred:           0.00 MB
Response time:              2.23 secs
Transaction rate:           3.48 trans/sec
Throughput:             0.00 MB/sec
Concurrency:                7.77
Successful transactions:          68
Failed transactions:               0
Longest transaction:            3.08
Shortest transaction:           1.16
```

If you need something faster then let me know. I prefer to keep the instances clean than get in the business of cleaning up after each instance.

**Comment by amir20** [comment] 2016-02-17 04:38
I am going to close this now that I have cookie support. If you performance test and it is slow then let's talk about how I can help you to improve it. I am not against having one instance per application. But starting phantom has usually been really cheap.

**Closed by amir20** 2016-02-17 04:38 UTC
