### ISSUE TITLE
phantom.createOutObject() is freeze function

### ISSUE THREAD

**Issue by ErickSkrauch** [amir20/phantomjs-node#418] opened 2016-03-19 19:58 UTC
### Expected behavior

I want to create out object for retrieve data from event onResourceReceived:

```js
let outObj = phantom.createOutObject();
console.log('still work?');
page.property('onResourceReceived', (resource, out) => {
    if (url !== resource.url || resource.redirectURL) {
        out.redirectURL = resource.redirectURL;
    }
}, outObj);
```

### Actual behavior

When the interpreter comes to call createOutObject() function is freeze and code below not performed.

### Steps to reproduce the behavior

1. Create browser
2. Create page
3. Use code above.

### Environment

- OS: Ubuntu 15.10 
- Node version (`node -v`): 4.4.0
- package version: 2.0.9

**Comment by amir20** [comment] 2016-03-21 05:16
I am not sure what you mean. It works for me. Maybe paste your whole code and not just part of it.

**Comment by amir20** [comment] 2016-03-21 15:42
Closing as not reproducible.

**Closed by amir20** 2016-03-21 15:42 UTC
Labels: invalid
