### ISSUE TITLE
how can i  use a spe variable  in  header or footer content callback 

### ISSUE THREAD

**Issue by ibeeger** [amir20/phantomjs-node#499] opened 2016-07-05 08:36 UTC
<pre>
            var title ="标题"
            var config = {
                width: "1040px",
                height: "1414px",
                borderLeft: "5px solid #000",
                margin: {
                    top: "0px",
                    left: "15px",
                    right: "5px",
                    bottom: "0px"
                },
                orientation: "portrait",
                header: {
                    height: 315,
                    contents: phInstance.callback(function(page, num) {
                    //这里的 title 获取不到 
                    return title;
                })
                },
                footer: {
                    height: 50,
                    contents: phInstance.callback(function(pageNum, numPages) {
                        return "<div style='border-top:8px dashed #000'></div><p style='text-align:center;'>底部" + pageNum + "/" + numPages + "</p>";
                    })
                }
            }
</pre>

**Comment by amir20** [comment] 2016-07-05 13:32
Sorry, I don't know what is spe variable?

**Comment by amir20** [comment] 2016-07-05 16:29
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com. 
Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future. 

This message is a saved reply and was posted automatically.

**Comment by amir20** [comment] 2016-07-05 16:29
I closed this issue because after search spe on google with phantomjs, I wasn't able to find anything. Please provide better detail and reopen.

**Closed by amir20** 2016-07-05 16:29 UTC
