### ISSUE TITLE
Fresh Install - SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by kicks66** [amir20/phantomjs-node#602] opened 2017-01-10 19:02 UTC
### Expected behavior

phantomjs-node runs

### Actual behavior

phantomjs-node fails to run

### Steps to reproduce the behavior

1) run `npm install phantom`
2) create script calling phantom
3) observe error

### Environment

- OS: Mac OSX Sierra
- Node version (`node -v`): 5.12.0
- package version: latest

Error:

```
phantom.js:77
    constructor(args = [], { phantomPath = _phantomjsPrebuilt2.default.path, logger = defaultLogger, logLevel = 'debug' } = {
                     ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xxx/Documents/Dojo/node-video-extractor-final/node_modules/phantom/lib/index.js:7:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by amir20** [comment] 2017-01-10 19:18
Latest version no longer supports Node v5. You should upgrade to Node v6. See #600.

**Comment by amir20** [comment] 2017-01-10 19:38
Closing since version `3.2.1` is an option to use with v5. Hopefully you can upgrade node because I don't plan to support older versions than 6.

**Closed by amir20** 2017-01-10 19:38 UTC

**Comment by snamoah** [comment] 2017-01-12 22:24
@amir20 having the same problem. node version is 6.9.2

**Comment by amir20** [comment] 2017-01-12 22:41
That's not good. @snamoah. But I wasn't able to reproduce it with https://raw.githubusercontent.com/amir20/phantomjs-node/master/examples/simple.js. It works fine for me with node 6.9.1. Can you share a script to reproduce?

**Comment by amir20** [comment] 2017-01-14 00:58
@snamoah I guess it worked for you?
