### ISSUE TITLE
Testing Dynamic DOM content on ASP.NET Pages

### ISSUE THREAD

**Issue by salmankhann** [amir20/phantomjs-node#615] opened 2017-02-22 16:52 UTC
I've noticed that PhantomJs does not read updated the DOM for ASP.NET pages.

### Expected behavior
1. Load https://m.novocinemas.com/mobile/MovieListView.aspx using phantomjs
2. Expect DOM content of div.select_cinema to be updated when retrieved using page.property('content') (the DOM content of div.select_cinema is updated due to a script on the webpage)

### Actual behavior
1. Load https://m.novocinemas.com/mobile/MovieListView.aspx using phantomjs
2. The DOM Content of div.select_cinema is empty as retrieved from the original page load.

### Steps to reproduce the behavior
1. Execute the following code
```
var phantom = require('phantom');

phantom.create().then(function (ph) {
    ph.createPage().then(function (page) {
        page.open('https://m.novocinemas.com/mobile/CinemaList.aspx').then(function (status) {
            console.log(status);
            setTimeout(() => { //just added for enough delay for the scripts to render
                page.property('content').then(function (content) {
                    console.log(content);
                    page.close();
                    ph.exit();
                });
            }, 5000)
        });
    });
});
```

Am I doing something wrong because the DOM does not seem to be updated after page scripts modify the page

### Environment

- OS: MacOS Sierra (10.12.3)
- Node version (`node -v`): 6.9.5
- package version: 4.0.0

**Comment by amir20** [comment] 2017-02-22 17:46
I think there is something going on with your page that is unrelated. I would first see if you can actually get this to work with plain phantomjs, without Node. If that works, paste the code so I can debug. That would be a bug. 

If that doesn't work then something is up with your dom, because I haven't been able to reproduce it.

**Comment by salmankhann** [comment] 2017-02-22 17:54
hmm let me try normal Phantomjs first and i"ll revert back here. Did you get a chance to try the script I posted above? Are you also getting the same behavior?

**Comment by amir20** [comment] 2017-02-22 18:38
I haven't had a chance to run it yet. But I remember seeing that this worked. Look at this code https://github.com/amir20/phantomjs-node/issues/431#issuecomment-207865947. Instead of timeout, you could do wait for object to be there. This was a while ago so I hope it works. 

I am at work, but maybe later I can run your script.

**Comment by amir20** [comment] 2017-02-22 18:39
Also, I don't think this is related to ASP. I went to https://m.novocinemas.com/mobile/CinemaList.aspx and nothing happened. Perhaps try a different page?

**Comment by amir20** [comment] 2017-03-01 15:45
Any reponse?

**Comment by salmankhann** [comment] 2017-03-01 17:27
Hi, I didn't get a chance to explore it further. Will do it this weekend and report back

Sent from my iPhone

On Mar 1, 2017, at 7:45 PM, Amir Raminfar <notifications@github.com<mailto:notifications@github.com>> wrote:


Any reponse?

**Comment by SvenAlHamad** [comment] 2017-03-01 20:54
I had the same issues ... but when I updated to phantomjs 2.5-beta (which supports ES6) it all worked fine and the content was updates. I tested by copy/pasting the upper code and just changing the url to my React app.

**Comment by amir20** [comment] 2017-03-01 21:10
@SvenAlHamad that's awesome. How did you upgrade to beta? It has been on my to do list for a while but haven't had a chance to play with it.

**Comment by SvenAlHamad** [comment] 2017-03-01 21:12
Good thing I noted everything in my evernote :)

so, I use ubuntu 16.04 and this are the steps:

download it from here:
https://bitbucket.org/ariya/phantomjs/downloads/
```
tar -zxvf {archive name here}

sudo apt-get install libstdc-dev
sudo apt-get install libwebp-dev
sudo apt-get install libhyphen-dev
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9 g++-4.9
sudo mv phantomjs-2.5.0-beta-ubuntu-trusty /usr/local/share/
sudo ln -sf /usr/local/share/phantomjs-2.5.0-beta-ubuntu-trusty/bin/phantomjs /usr/local/bin
phantomjs --version
```

**Comment by amir20** [comment] 2017-03-01 23:49
oh nice!

**Comment by amir20** [comment] 2017-03-01 23:49
Marking as an upstream dependency since phantom seems to have fixed it.

**Comment by amir20** [comment] 2017-03-03 18:43
OK I think it's safe to close this since we know Beta fixes it.

**Closed** 2017-03-03 18:45 UTC
Labels: Awaiting Response, Cannot Reproduce, Upstream Dependency
