### ISSUE TITLE
paperSize height property error

### ISSUE THREAD

**Issue by solcius117** [amir20/phantomjs-node#411] opened 2016-03-16 05:07 UTC
I'm trying to set a header for a pdf render but I believe I´m doing something wrong:

```
page.property("paperSize", {
                        format: 'A4',
                        orientation: 'portrait',
                        margin: '1cm',
                        header: {
                            height: "2cm"
                        }
});
```
The header.height property works, but I get the following error:

```
SyntaxError: Unexpected EOF
undefined:1 in render
phantomjs://code/shim.js:132 in executeCommand
phantomjs://code/shim.js:112 in read
```
Also, how should I send the phantom.callback object in the contents property?

**Comment by amir20** [comment] 2016-03-16 16:08
I can confirm that I can reproduce this. :( Let me look into it. 

`phantom.callback` is not supported right now. It wouldn't be hard to add though.

**Comment by amir20** [comment] 2016-03-16 16:49
This had me stumped for a while. Until I just decided to reproduce this with vanilla phantomjs. 

```js
var webPage = require('webpage');
var page = webPage.create();
page.paperSize = {
    format: 'A4',
    orientation: 'portrait',
    margin: '1cm',
    header: {
        height: '2cm'
    }
};

page.open("http://www.google.com", function(status) {
    page.render('google.pdf');
    phantom.exit();
});
```
Which produces
```
~/D/test_phantom $ phantomjs phantom.js 
SyntaxError: Unexpected EOF
  undefined:1 in render
  phantomjs://code/phantom.js:15
  phantomjs://platform/webpage.js:286 in _onPageOpenFinished
```

So I can confirm that this is a problem with `phantimjs` :(

**Comment by solcius117** [comment] 2016-03-16 20:46
Adding the contents property also works fine.

```
var webPage = require('webpage');
var page = webPage.create();
page.paperSize = {
    format: 'A4',
    orientation: 'portrait',
    margin: '1cm',
    header: {
        height : '2cm',
        contents : phantom.callback(function(pageNum, numPages){
            return "<span>" + pageNum + "/" + numPages + "</span>";
        })
    }
};

page.open("http://www.google.com", function(status) {
    page.render('google.pdf');
    phantom.exit();
});
```

**Comment by amir20** [comment] 2016-03-16 20:52
Interesting. Then I guess you can wait until #415 is fixed.

**Comment by amir20** [comment] 2016-03-17 15:28
#416 is merged. `2.0.7` should be live soon.

**Closed** 2016-03-17 15:29 UTC
Labels: bug, upstream

**Comment by loretoparisi** [comment] 2016-04-05 14:04
@amir20 is the same issue?

```shell
ReferenceError: Can't find variable: uuid

  phantomjs://platform/test.js:73
  phantomjs://platform/webpage.js:286 in _onPageOpenFinished
ReferenceError: Can't find variable: uuid
```

**Comment by amir20** [comment] 2016-04-05 16:50
No that's not related. I am not sure what is `webpage.js:286`. I dont have that file name.

**Comment by loretoparisi** [comment] 2016-04-06 10:17
@amir20 I think this could be a `phantomjs` file when doing `var page = require('webpage').create()`

**Comment by amir20** [comment] 2016-04-06 15:39
Hmmm, then it might be something in `phantomjs`. I wouldn't know exactly. I don't use UUID anywhere.

**Comment by nchorrigan** [comment] 2016-10-13 09:36
The 'Unexpected EOF' warning is caused by there being no content being returned for a header.  Can be replicated by either specifying no fixed 'contents' or no string being returned by a phantom.callback

E.g.

`header: {
      height: "5cm",			
      contents: phantom.callback(function(pageNum, numPages) {
		if(pageNum == 1) {
			return "";
		}				
		return "";  //You've got to return something
     })
}`
