### ISSUE TITLE
Getting error while page.open() method.

### ISSUE THREAD

**Issue by CodEzyGit** [amir20/phantomjs-node#597] opened 2016-12-12 10:59 UTC
on page.open() method getting error as 
(STDERR) error: select: Invalid argument

**Comment by KpjComp** [comment] 2016-12-12 14:39
Is that you full code,.. ?

`page.open()`  expects a url..  eg.  `page.open('http://www.google.com')`

**Comment by CodEzyGit** [comment] 2016-12-12 15:13
Yes correct, I have called same as you specified.

**Comment by KpjComp** [comment] 2016-12-12 15:18
Can we see the rest of  your code, because `page.open()` obviously works, or nobody would be able to render anything.

Are you sure the parameter your passing to open is a string?.

**Comment by CodEzyGit** [comment] 2016-12-12 18:22
It should work, but don't know why it is failing down in my code. Actually page.evaluate() method works but it fails for page.open(). I am passing parameter as an string.

**Comment by amir20** [comment] 2016-12-12 20:00
I copied your code and it works. So I don't know what you are doing. It looks like it's related to something you are doing wrong. You have to provide an example that is isolated for other to reproduce. It looks like the example you provided is from the example folder. So I don't know what your code looks like. 

Going forward, if you want support, please follow the template. 

Closing...

**Closed by amir20** 2016-12-12 20:00 UTC
Labels: Cannot Reproduce
