### ISSUE TITLE
page.pages[0].evaluate is not a function

### ISSUE THREAD

**Issue by Vinayk93** [amir20/phantomjs-node#633] opened 2017-03-23 11:06 UTC
page.pages[0].evaluate need to act similar as page.evaluate

### Actual behavior

it doesnot recognise the function evaluate inside page.pages[0]

### Steps to reproduce the behavior

1. create a pages inside page
2. inject js inside one tab
3. then inject another js inside another tab

- OS: mac and ubuntu
- Node version (`node -v`): 6.9.5
- package version: 4.0.1

**Comment by elias-winberg** [comment] 2017-03-23 11:29
`pages` isn't even a property that exists. The functionality you are looking for must be added via a PR.

**Comment by amir20** [comment] 2017-03-23 15:22
Thanks @elias-winberg. This a duplicate of #614. I am not sure what was the purpose of opening a duplicate ticket. As others have suggested, and I have suggested in #614, this functionality is not _implemented_ right now. It would be very hard for `page.pages[0]` to work exactly as is because all calls are proxied to another process. 

Please send a PR if you like to see this implemented. I can help you get it tested, approved and deployed. Most likely something likely, it would need to be `page.pages(0)` instead of `[0]` because node doesn't have access to inner array of phantom.

**Closed by amir20** 2017-03-23 15:22 UTC
