### ISSUE TITLE
phantom.create( is not running  it is not displaying "phantom" in console.log 

### ISSUE THREAD

**Issue by awesomehimanshu** [amir20/phantomjs-node#504] opened 2016-07-12 12:04 UTC
I am using phantom to generate pdf . phantom.create( is not running  it is not displaying "phantom" in console.log 

phantom.create(function(ph) {
    console.log("phantom");
  ph.createPage(function(page) {
    page.open("http://www.google.com", function(status) {
      console.log("opened google? ", status);
      page.evaluate((function() {
        return document.title;
      }), function(result) {
        console.log('Page title is ' + result);
        ph.exit();
      });
    });
  });
});

### Environment

- OS: ubuntu 14.04
- Node version (`node -v`): 5.5
- package version:

**Comment by amir20** [comment] 2016-07-12 18:19
Your question is not very clear. I don't know what you are asking and I find it every confusing. The code your provided won't work because it is not using Promises like the README suggests. Please ask better questions so that others can help you. I am closing.

**Closed by amir20** 2016-07-12 18:19 UTC

**Comment by amir20** [comment] 2016-07-12 19:05
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com. 
Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future. 

This message is a saved reply and was posted automatically.
