### ISSUE TITLE
Phantom process stopped with exit code 3221225477

### ISSUE THREAD

**Issue by keyiis** [amir20/phantomjs-node#718] opened 2017-12-24 15:57 UTC
```
Error: Phantom process stopped with exit code 3221225477
    at commands.forEach.command (D:\work\nodejs\ctrip_spider\node_modules\phantom\lib\phantom.js:358:33)
    at Map.forEach (<anonymous>)
    at Phantom.rejectAllCommands (D:\work\nodejs\ctrip_spider\node_modules\phantom\lib\phantom.js:355:19)
    at ChildProcess.Phantom.process.on.code (D:\work\nodejs\ctrip_spider\node_modules\phantom\lib\phantom.js:148:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```
### Environment

- OS:win10 x64
- Node version (`node -v`):8.9.3
- package version: 4.0.12

**Comment by amir20** [comment] 2017-12-27 16:25
I am not sure how to reproduce this. It looks like it’s related to phantomjs process more than node.

**Comment by amir20** [comment] 2017-12-29 17:09
After some googling, this looks to be a bug with with phantomjs. https://github.com/gmetais/YellowLabTools/issues/150 So closing....

**Closed by amir20** 2017-12-29 17:09 UTC
Labels: Awaiting Response, Cannot Reproduce, Upstream Dependency
