### ISSUE TITLE
phantomjs process hangs and not work in the multiprocess enviroment

### ISSUE THREAD

**Issue by yinguangluoren** [amir20/phantomjs-node#703] opened 2017-10-26 05:41 UTC
when i use phantomjs-node to print a web page to pdf,  my work needs to call phantomjs many times in fews seconds, and i found that the function which create phantom instance and does core work did not perform well when i test thirty seconds, 1 request per second with no waiting for response and the some phantom process hangs and did not work . Here is my code , could you tell me how i can do to improve the performance of phantom under high concurrency environment.thanks!

`
var restify = require('restify'), // restful web services
phantom = require('phantom'),
fs = require('fs');
var log4js = require('log4js');

log4js.configure({
    appenders: { cheese: { type: 'file', filename: '/home/cheese.log' } },
    categories: { default: { appenders: ['cheese'], level: 'debug' } }
  });
var logger = log4js.getLogger('cheese');

var _that = this;

var server = restify.createServer();
server.listen(8089, function () {
    logger.debug("port open！！！");
});

server.get('/ui/:_url', function (req, res) {
   var _url = req.params._url;
  phantom_loads_page(
    _url,
    function (_response) {
          logger.info("response is "+ _response);
          if(_response == TIMEOUT) {
            logger.info("retry again");
            phantom_loads_page(_url, function(_response) {
                logger.info("response is "+ _response);
                res.json(_response);
            });
          }
            res.json(_response);
            return;
        }
    );
});

var phantom_loads_page = function(_url,api_callback){
    phantom.cookiesEnabled = true;
    phantom.create(['--ignore-ssl-errors=yes'], {
    }).then(function (ph) {
        ph.createPage().then(function (page) {
                    page.open(_url, "GET").then(function (status){
                        if (!status || status == 'fail') {
                            
                            logger.error("Fail to open url"+url);
                            ph.exit();
                            api_callback("FAIL_TO_OPEN: " + _url);
                        } else {
                           logger.info("open url" + _url);
    
                            page.evaluate(function () {
                                var style = document.createElement('style'),
                                    text = document.createTextNode('@media print { html { zoom: 0.68; margin: 1cm; } }');
                                style.setAttribute('type', 'text/css');
                                style.appendChild(text);
                                document.head.insertBefore(style, document.head.firstChild);
                            });
                           
                            page.property('paperSize', {
                                format: 'A3', orientation: 'portrait',
                                margin: {left: "0", right: "0cm", top: "0cm", bottom: "0cm"},
                                header: {
                                    height: "0.5cm",
                                    contents: ph.callback(function (pageNum, numPages) {
                                        return "";
                                    })
                                },
                            });

                            page.property('zoomFactor', 1);
                            var _filename = _url + ".pdf" ;
                            page.on('onConsoleMessage', function (msg) {
                                if (msg == "LOGS_LOADED") {
                                    logger.info("Logs load status: " + msg );
                                    //Wait 1 second in case of DOM is not refresh after data received
                                        page.render(__dirname + "/generated_reports/" + _filename);
                                        ph.exit();
                                        api_callback("success");
                                } else if (msg == "LOGS_LOADED_FAIL") {
                                    rendered = true;
                                    logger.error("Fail to load logs data: " + msg);
                                   
                                    ph.exit();
                                    api_callback("LOGS_LOADED_FAIL");
                                } else {
                                    logger.error("Not logs load: " + msg);
                                }
                            });
                            //If no logs shown after 60 seconds, return fail
                            setTimeout(function () {                    
                                    logger.error("timeout Didn't get logs load signal after 60 seconds,");
                                    ph.exit();
                                    api_callback("DID_NOT_GET_LOGS_LOAD_SIGNAL");
                            }, 60000);

                        }
                    }).catch(function (err) {
                        logger.error("fail to open "+ _url);
                        
                    });
                    
            }).catch(function (err) {
                logger.error("Phantom instance fail to create page");
                ph.exit();
               
            });
        }).catch(function (err) {
            logger.error("Fail to create phantom instance");           
        });
};`

### Environment

- OS: redhat
- Node version (`node -v`): 6.11.3
- package version: 4.0.5

**Comment by amir20** [comment] 2017-10-26 15:04
Try using a pool https://github.com/amir20/phantomjs-node#pooling. Closing as this is not a bug.

**Closed by amir20** 2017-10-26 15:04 UTC
