### ISSUE TITLE
How to filter network requests and abort specific requests on 'onResourceRequested'

### ISSUE THREAD

**Issue by prastut** [amir20/phantomjs-node#681] opened 2017-07-10 10:21 UTC
@amir20 I tried working with your given example in #524 . Snippet:

```
 let _ph, _page, _outObj, regex = '^http(s)?://(www|ssl)\.google-analytics\.com.*';

    phantom.create().then(ph => {
        _ph = ph;
        return _ph.createPage();
    }).then(page => {
        _page = page;
        _outObj = _ph.createOutObject();

        _outObj.urls = [];

        page.on('onResourceRequested', true, function(requestData, request, regex) {
            var url = requestData['url'];
            var re = new RegExp(regex, 'ig');
            var isBlacklisted = re.test(url);
            if (isBlacklisted) {
                request.abort();
            }
        }, regex);

        return _page.open('https://prastut.github.io');
    }).then(status => {
        return _outObj.property('urls');
    }).then(urls => {

        console.log(urls);

        _page.close();
        _ph.exit();
    }).catch(console.error);
```

Gives me the following error:
```
undefined is not an object (evaluating 'objectSpace[command.target][command.params[0]]')
    at Stream.Phantom.process.stdout.pipe.on.data (/Users/prastutkumar/Dev/intercept/node/node_modules/phantom/lib/phantom.js:137:45)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at drain (/Users/prastutkumar/Dev/intercept/node/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/Users/prastutkumar/Dev/intercept/node/node_modules/through/index.js:45:5)
    at emit (/Users/prastutkumar/Dev/intercept/node/node_modules/split/index.js:37:14)
    at next (/Users/prastutkumar/Dev/intercept/node/node_modules/split/index.js:49:7)
    at Stream.<anonymous> (/Users/prastutkumar/Dev/intercept/node/node_modules/split/index.js:54:5)
    at Stream.stream.write (/Users/prastutkumar/Dev/intercept/node/node_modules/through/index.js:26:11)
    at Socket.ondata (_stream_readable.js:555:20)

```

Usecase: I want to filter out requested resources and abort the ones I do not want. I wrote a simple phantomJS script to do the same and it works. Have explained the snippet in comments:

```
// runs as phantomjs <filename>.js <url>

var resources_to_log = [
    new RegExp('^http(s)?://(www|ssl)\.google-analytics\.com.*'),
    new RegExp('^http(s)?://stats\.g\.doubleclick\.net.*')
];

page.onResourceRequested = function(request) {

        if (system.args[1] == request.url) {
           // if it's the requested URL only
            return;
        } else if (isImg(request.url) || isExt(request.url, 'js') || isExt(request.url, 'css') || isExt(request.url, 'woff')) {
            // Checks for extensions and if they are js, image (jpg,png), css, woff, the network requests should be rejected   
            networkRequest.abort();
        } else {

            var length = resources_to_log.length;
            while (length--) {
                if (resources_to_log[length].test(request.url)) {
                   //Outputs the URL I want
                    console.log(request.url)
                    phantom.exit();
                }
            }
        }

    };

```

- OS: Mac OS Sierra 
- Node version (`node -v`): v6.10.0
- package version: 4.0.4

**Comment by amir20** [comment] 2017-07-11 18:11
So I used

```js
const phantom = require('phantom') 
 
 let _ph, _page, _outObj, regex = '^http(s)?://(www|ssl)\.google-analytics\.com.*';

    phantom.create().then(ph => {
        _ph = ph;
        return _ph.createPage();
    }).then(page => {
        _page = page;                

        page.on('onResourceRequested', true, function(requestData, request, regex) {
            console.log(regex);
            var url = requestData['url'];
            var re = new RegExp(regex, 'ig');
            var isBlacklisted = re.test(url);
            if (isBlacklisted) {
                request.abort();
            }
        }, regex);

        return _page.open('https://prastut.github.io');
    }).then(urls => {        
        _page.close();
        _ph.exit();
    }).catch(console.error);
```

And it worked. I don't think your problem is with `onResourceRequested`. I noticed you are not using `_outObj.urls` at all.  I'll keep this open for now because I don't know what your problem is. You should do some debugging and see if you reproduce this with only minimum part of the code.

**Comment by prastut** [comment] 2017-07-13 12:49
@amir20 your example works for me as well 😅 . 

Okay so I followed your advice and brought it debugged it down to where it is having problems:

```
   let _ph, _page, _outObj, regex = '^http(s)?://(www|ssl)\.google-analytics\.com.*';

    phantom.create().then(ph => {
        _ph = ph;
        return _ph.createPage();
    }).then(page => {
        _page = page;
        _outObj = _ph.createOutObject();

        _outObj.urls = [];

        page.on('onResourceRequested', true, function(requestData, request, regex, _outObj) {
            var url = requestData['url'];
            var re = new RegExp(regex, 'ig');
            var isBlacklisted = re.test(url);
            if (isBlacklisted) {
                _outObj.push(requestData['url']);
            }
        }, regex, _outObj);

        return _page.open('https://prastut.github.io');
    }).then(status => {
        return _outObj.property('urls');
    }).then(urls => {
        console.log(urls);
        _page.close();
        _ph.exit();
    }).catch(console.error);
```
This is not working and I was going though the documentation and I found this:

```
page.on('onResourceRequested', true, function (requestData, networkRequest) {
    urls.push(requestData.url); // now this wont work, because this function would execute in phantom runtime and thus wont have access to the closure.
    networkRequest.abort(); // This would work, because you are accessing to the non serialized networkRequest.
});

page.load('http://google.com');
```

Probably the push is not working due to the reason mentioned in the example above. Is there a some way around this? 

Also when I try your code only by modifying a little for my usecase. 
Usecase: I need to log the google analytics request that is being generated. 
* To increase performance of the logger as well as not hitting the GA servers as this is debugging, I decided to abort all requests. 
* So Phantom parses all request generated -> checks for GA link by regex -> aborts all requests. 
* As soon as GA link is found, Phantom should exit as it should not allow next incoming requests since my job is done. 

I am doing the above in PhantomJS like this:

```
var url;

page.onResourceRequested = function(request) {

        if (system.args[1] == request.url) {
            return;
        } else if (isImg(request.url) || isExt(request.url, 'js') || isExt(request.url, 'css') || isExt(request.url, 'woff')) {
            // console.log(request.url);
            networkRequest.abort();
        } else {

            var length = resources_to_log.length;
            while (length--) {
                if (resources_to_log[length].test(request.url)) {
                    url = request.url;
                
                    phantom.exit();
                }
            }
        }

    };

```

I want to do the same using the phantomjs-node.

**Comment by amir20** [comment] 2017-07-25 17:57
What's the update on this? I was out for a while and haven't had a chance to look at it? Did you have any chance to debug or look more?

**Comment by prastut** [comment] 2017-07-25 20:10
@amir20 please have a look through the [above](https://github.com/amir20/phantomjs-node/issues/681#issuecomment-315067804) comment. I was hoping if you could shine some light on the points I mention. I didn't debug it more because I had no clue how to proceed (right now using the PhantomJS code that I mention in the issue)

**Comment by amir20** [comment] 2017-07-26 02:11
I changed `page.on` to `page.property` and it seemed to have worked. At least no error. Then I realized you had a typo. It should be `_outObj.urls.push(url);` inside your `if` statement. 

What's going on here is the `property` is much older that `on` because that functionality was added much later. I could use some help fixing the documentation. 

Here is the final js

```js
const phantom = require('phantom');


   let _ph, _page, _outObj, regex = '^http(s)?://(www|ssl)\.google-analytics\.com.*';

    phantom.create().then(ph => {
        _ph = ph;
        return _ph.createPage();
    }).then(page => {
        _page = page;
        _outObj = _ph.createOutObject();

        _outObj.urls = [];

        page.property('onResourceRequested', function(requestData, request, regex, _outObj) {
            var url = requestData['url'];
            var re = new RegExp(regex, 'ig');
            var isBlacklisted = re.test(url);
            if (isBlacklisted) {
                _outObj.urls.push(url);
            }
        }, regex, _outObj);

        return _page.open('https://prastut.github.io');
    }).then(status => {
        return _outObj.property('urls');
    }).then(urls => {
        console.log(urls);
        _page.close();
        _ph.exit();
    }).catch(console.error);
```

**Comment by amir20** [comment] 2017-07-26 02:12
Can you me out and up the README?

**Comment by amir20** [comment] 2017-07-26 16:33
@prastut ping

**Comment by prastut** [comment] 2017-07-26 17:34
@amir20 hey sorry! Will do that right now.

**Comment by prastut** [comment] 2017-07-26 18:16
@amir20 referring to your code:

```
  page.property('onResourceRequested', function(requestData, request, regex, _outObj) {
            var url = requestData['url'];
            var re = new RegExp(regex, 'ig');
            var isBlacklisted = re.test(url);
            if (isBlacklisted) {
                _outObj.urls.push(url);
            }
        }, regex, _outObj);
```

^ The above piece of code works but it is still very inefficient in terms of the scope of the usecase that  'onResourceRequested' provides. What the above piece of code will do is that it will request all resources and let them complete, just filter out the request we want. The efficient way would be to abort all the requests that are not being validated by the regex and filter the request we want, therefore saving countless HTTP requests in the process. 

Let me know what you think about this.

**Comment by amir20** [comment] 2017-07-27 16:27
I don't understand what you are doing. I copied your code from the [comment above](https://github.com/amir20/phantomjs-node/issues/681#issuecomment-315067804) and made it work with `property`. You didn't call in `request.abort()` in the code that you posted earlier. Now that `page.property` works then why can't you just call `abort()`? Like this as an example...

```js
page.property('onResourceRequested', function(requestData, request, regex, _outObj) {
            var url = requestData['url'];
            var re = new RegExp(regex, 'ig');
            var isBlacklisted = re.test(url);
            if (isBlacklisted) {
                request.abort() // <---- this
                _outObj.urls.push(url);
            }
        }, regex, _outObj);
```

I was hoping you can help me to deprecate `property` because it seems like `property` vs `on` is confusing people. I need to fix the bug that doesn't let you use `OutputObj` in `on` first. 

You should spend some time reading this repo. I won't have time to go through your usecase this week. I would appreciate if you actually understand what's going on. And then send a pull request if you figure out what is not working. That's what most people have done so far which has helped me a lot.

**Comment by amir20** [comment] 2017-07-28 16:51
I am going to close this soon if I don't hear back...

**Comment by prastut** [comment] 2017-07-28 17:20
@amir20 I have my exams coming up, so I won't have time right now. But afterwards I promise to fix the bug you mention. You can close it for now if you feel like.

**Closed** 2017-07-28 22:24 UTC
Labels: Awaiting Response, Cannot Reproduce
